{
  "hash": "008376d8e7f6db697a7e8da9e09d355e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Sprawozdanie Quarto+R\"\nsubtitle: \"Kurs\"\nauthor: \"Szymon Maślanka\"\ndate: today\nabstract-title: Abstrakt\nabstract: Poniżej znajduje się sprawozdanie na podstawie wytycznych z platformy UPEL zawierające opis czegoś o mnie przy wykorzystaniu poznanych informacji i prezentacja poznanej wiedzy, a na końcu przeprowadzona regresja liniowa na zestawie danych.\nformat: \n  html:\n    toc: true\n    toc-title: \"Spis treści\"\n    toc-location: right\n    toc-depth: 4\n    number-sections: true\n    number-depth: 4\n    embed-resources: true\n    self-contained-math: true\n    html-math-method: katex\n    theme: Yeti\n    anchor-sections: true\n    code-fold: show\n    fig-align: center\n    lang: pl\nexecute:\n  echo: true\n  warning: false\neditor_options: \n  \n  chunk_output_type: console\n---\n\n```{=html}\n<style>\n  body {\n    text-align: justify;\n  }\n</style>\n```\n\n\n\n## Pakiety {.unnumbered .unlisted}\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(tidyverse)\nlibrary(leaflet)\nlibrary(htmlwidgets)\nlibrary(HistData)\nlibrary(DT)\nlibrary(purrr)\nlibrary(readr)\nlibrary(stringr)\nlibrary(broom)\nlibrary(skimr)\nlibrary(lmtest)\nlibrary(ggfortify)\nlibrary(plotly)\n```\n:::\n\n\n\n## Nagłówek YAML\n\nPowyższy informacje oraz formatowanie strony zostało wykonane przy użcyiu nagłówka YAML:\n\n``` yaml\n---\ntitle: \"Sprawozdanie Quarto+R\" # Tytuł dokumentu\nsubtitle: \"Kurs\" # Podtytuł dokumentu\nauthor: \"Szymon Maślanka\" # Autor dokumentu\ndate: today # Data publikacji dokumentu\nabstract-title: Abstrakt # Tytuł streszczenia\nabstract: Poniżej znajduje się sprawozdanie na podstawie wytycznych z platformy UPEL zawierające opis czegoś o mnie przy wykorzystaniu poznanych informacji, a na końcu przeprowadzona regresja liniowa na zestawie danych. # Treść streszczenia\nformat: # Dokument zostanie wygenerowany do formatu HTML\n  html:\n    toc: true  # Aktywny spis treści\n    toc-title: \"Spis treści\"  # Tytuł spisu\n    toc-location: right # Lokalizacja spisu po prawej\n    toc-depth: 4 # Nagłówki w spisie znajdują się do nagłówka 4 stopnia\n    number-sections: true  # Nagłówki są numerowane\n    number-depth: 4 # Nagłówki numerowane od 1-4 stopnia\n    embed-resources: true # Plik HTML będzie samowystarczalny\n    self-contained-math: true  # Do samowystarczalności zaliczają się też biblioteki matematyczne\n    html-math-method: katex # Katex jako metoda do renderowania matematyki\n    theme: Yeti # Styl dokumentu Yeti\n    anchor-sections: true # Po najechaniu na nagłówek wyświetla link kotwiczący\n    code-fold: show # Pozwala chować i rozwijać kod na stronie\n    fig-align: center # Domyślne obrazy wycentrowane\n    lang: pl # Domyślny język dokumentu Polski\nexecute: # Domyślne opcje kodu w dokumencie\n  echo: true # Wyświetla kod\n  warning: false # Nie wyświetla ostrzeżeń\neditor_options:  # Opcje edytora\n  chunk_output_type: console # Wyniki kodu wyświetlane surowo(tekst)\n---\n```\n\n## Zainteresowania - cogito ergo sum\n\nHej! Mam na imię **Szymon Maślanka** i w sierpniu zacznę *22 lata*. Jestem studentem na **AGH** w Krakowie, na kierunku ***WIMiIP ETI***. Moje zainteresowania to:\n\n-   Zwierzęta głównie:\n    -   Gryzonie\n    -   Akwarystyka\n-   Gra na gitarze\n-   Jazda na rowerze\n\n:::::: panel-tabset\n### Akwarystyka\n\nAkwarystyka to moja pasja od wielu lat. Dbam o swoje dwa akwaria słodkowodne, starając się zapewnić jak najlepsze warunki dla ryb i roślin. To dla mnie forma relaksu i odpoczynku.\n\n::: {#fig-akwaria layout-ncol=\"2\"}\n![Akwarium1](akwa1.jpeg){#fig-akwa1 .lightbox width=\"100%\" fig-alt=\"Akwarium1\"}\n\n![Akwarium2](akwa2.jpg){#fig-akwa2 .lightbox width=\"90%\" fig-alt=\"Akwarium2\"}\n\nMoje rybki\n:::\n\nPolecam tę stronę dotyczącą wiedzy o gatunkach ryb:\n\n::: {style=\"text-align: center\"}\n[rybyakwariowe.eu](https://rybyakwariowe.eu)\n:::\n\n### Myszoskoczki\n\nMyszoskoczki to niesamowite stworzenia, które są moimi towarzyszami w domu. Lubię obserwować ich codzienne zachowanie.\n\n![Myszoskoczki](https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Mongolische_Wuestenrennmaus.jpg/500px-Mongolische_Wuestenrennmaus.jpg){fig-alt=\"Myszoskoczki\"}\n\nJeśli ktoś by zechciał również zostać właścicielem tutaj można adoptować:\n\n::: {style=\"text-align: center\"}\n[![Adoptuj](adopt.png)](https://labrescue.pl/porady/myszoskoczki/)\n:::\n\n### Gitara\n\nGitara to instrument, na którym grałem od wielu lat. Lubię grać różne piosenki, od rocka po ballady. Gram na gitarze akustycznej.\n\n![Moja gitara](Marti.jpg){fig-align=\"center\" width=\"20%\" fig-alt=\"Gitara\"}\n\n### Jazda na rowerze\n\nJazda na rowerze to moja ulubiona forma aktywności fizycznej. Przejażdżki po malowniczych trasach to doskonały sposób na odpoczynek.\n\n##### Mapa ścieżek rowerowych świata z zaznaczoną moją ulubioną ścieżką (z Muszyny do Krynicy) {.unnumbered .unlisted}\n\n\n\n::: {.cell .column-screen}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"leaflet html-widget html-fill-item\" id=\"htmlwidget-d58c5a6165084f4a6b09\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-d58c5a6165084f4a6b09\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}}},\"calls\":[{\"method\":\"addTiles\",\"args\":[\"https://tile.thunderforest.com/cycle/{z}/{x}/{y}.png?apikey=154813b0f2664b2ba4cda834a70df8cf\",null,null,{\"minZoom\":0,\"maxZoom\":18,\"tileSize\":256,\"subdomains\":\"abc\",\"errorTileUrl\":\"\",\"tms\":false,\"noWrap\":false,\"zoomOffset\":0,\"zoomReverse\":false,\"opacity\":1,\"zIndex\":1,\"detectRetina\":false,\"attribution\":\"Map data © OpenCycleMap, OpenStreetMap contributors\"}]},{\"method\":\"addLegend\",\"args\":[{\"colors\":[\"red\",\"purple\",\"blue\"],\"labels\":[\"Narodowe ścieżki rowerowe\",\"Regionalne ścieżki rowerowe\",\"Lokalne ścieżki rowerowe\"],\"na_color\":null,\"na_label\":\"NA\",\"opacity\":0.5,\"position\":\"bottomright\",\"type\":\"unknown\",\"title\":\"Legenda\",\"extra\":null,\"layerId\":null,\"className\":\"info legend\",\"group\":null}]},{\"method\":\"addMarkers\",\"args\":[[49.353301,49.421136],[20.891092,20.960063],null,[\"marker1\",\"marker2\"],null,{\"interactive\":true,\"draggable\":false,\"keyboard\":true,\"title\":\"\",\"alt\":\"\",\"zIndexOffset\":0,\"opacity\":1,\"riseOnHover\":false,\"riseOffset\":250},[\"\",\"\"],null,null,null,[\"Początek ulubionej trasy 🚴(Kliknij by przybliżyć)\",\"Koniec ulubionej trasy 🏁(Kliknij by przybliżyć)\"],{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]}],\"setView\":[[49.38,20.95],12,[]],\"limits\":{\"lat\":[49.353301,49.421136],\"lng\":[20.891092,20.960063]}},\"evals\":[],\"jsHooks\":{\"render\":[{\"code\":\"function(el, x, data) {\\n  return (function(el, x) {\\n    var map = this;\\n    map.on('popupopen', function(e) {\\n      map.setView([49.380, 20.9500], 12);\\n      e.target.closePopup();\\n    });\\n  }).call(this.getMap(), el, x, data);\\n}\",\"data\":null}]}}</script>\n```\n\n:::\n:::\n\n\n::::::\n\n::: callout-note\nDodatkowo dodam, że jestem jedynakiem.\n:::\n\n## Zawartość - pokaż co potrafisz\n\n### Pozyskanie danych, przetwarzanie potokowe (dplyr) i interaktywna tabela\n\nWykorzystałem zestaw danych \"GaltonFamilies\" z pakietu \"HistData\". Przy wykorzystaniu poniższych komend wyciągnąłem dane o wzroście ojca,matki i średniego wzrostu ich synów w centymetrach. Zestaw ten opisuje zależność między wzrostem rodziców a ich dzieci. Na końcu stworzyłem interaktywną tabele za pomocą pakietu [DT](https://rstudio.github.io/DT/){target=\"_blank\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- GaltonFamilies |>\n  as_tibble() |> \n  filter(gender==\"male\") |> \n  select(!children:childNum) |> \n  group_by(family) |> \n  summarize(\n    Wzrost_ojca = first(father),\n    Wzrost_matki = first(mother),\n    Średni_wzrost_synów = mean(childHeight, na.rm = TRUE)\n  ) |> \n  select(!family) |> \n  mutate(across(\n    .cols = where(is.numeric),\n    .fns = ~round(as.numeric((.x*2.54),digits=2),2)\n  ))\n  \n\na |> DT::datatable(options = list(scrollX = TRUE))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-5e0282467da1b3a2a8a5\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-5e0282467da1b3a2a8a5\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\"],[199.39,191.77,190.5,190.5,190.5,187.96,187.96,185.42,185.42,185.42,185.42,185.42,184.66,182.88,182.88,182.88,182.88,182.88,182.88,184.15,182.88,182.88,180.34,180.34,180.34,180.34,180.34,180.34,182.12,180.34,181.61,181.61,180.34,182.12,180.34,181.61,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,177.8,177.8,177.8,177.8,177.8,179.07,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,179.07,177.8,177.8,177.8,179.07,179.07,177.8,177.8,177.8,179.07,178.56,179.07,177.8,177.8,177.8,177.8,175.26,175.26,175.26,175.26,175.26,175.26,176.53,175.26,176.53,175.26,175.26,176.53,175.77,175.26,175.26,175.26,175.26,175.26,176.53,175.26,176.53,175.26,175.26,176.53,175.26,175.26,175.26,175.26,174.5,173.99,173.99,172.72,172.72,172.72,172.72,173.99,172.72,173.99,172.72,172.72,172.72,172.72,173.99,172.72,172.72,172.72,172.72,173.99,172.72,173.23,172.72,174.5,172.72,172.72,172.72,172.72,172.72,173.99,172.72,170.18,170.18,170.18,170.18,170.18,170.18,170.18,171.45,170.18,170.18,170.18,171.45,170.18,167.64,167.64,167.64,167.64,168.91,167.64,167.64,168.91,168.91,167.64,167.64,167.64,167.64,165.1,165.1,165.1,165.1,165.1,165.1,165.1,165.1,165.1,166.37,166.37,162.56,162.56,162.56,162.56,157.48,158.75],[170.18,168.91,162.56,162.56,148.59,172.72,157.48,170.18,170.18,168.91,165.1,163.83,175.26,172.72,170.18,165.1,160.02,160.02,160.02,157.48,157.48,157.48,175.26,170.18,167.64,167.64,167.64,167.64,166.37,166.37,166.37,165.1,165.1,163.83,162.56,163.83,163.83,161.29,160.02,160.02,157.48,157.48,158.75,157.48,147.32,175.26,175.26,172.72,170.18,168.91,165.1,165.1,165.1,165.1,165.1,165.1,165.1,164.34,162.56,162.56,163.07,162.56,162.56,162.56,161.8,160.02,160.02,161.29,160.02,160.02,157.48,159.26,157.48,154.94,152.4,148.59,147.32,173.99,167.64,167.64,169.42,167.64,168.91,168.91,168.91,167.64,167.64,165.1,163.83,162.56,160.02,160.02,160.02,161.29,161.29,157.48,157.48,157.48,158.75,157.48,154.94,154.94,152.4,152.4,153.67,179.07,170.18,168.91,165.1,166.37,166.37,165.1,165.1,162.56,165.1,162.56,162.56,162.56,160.02,161.29,160.02,160.02,160.02,160.02,161.29,160.02,161.29,158.75,157.48,158.75,154.94,152.91,152.4,152.4,149.86,149.86,168.15,168.91,167.64,165.1,166.37,166.37,165.1,165.1,162.56,161.29,160.02,157.48,154.94,170.18,170.18,167.64,167.64,165.1,166.37,160.02,160.02,158.75,156.21,152.4,152.4,149.86,170.18,167.64,167.64,165.1,166.37,165.1,162.56,160.02,160.02,160.02,152.4,162.56,162.56,160.02,152.4,167.64,160.02],[185.93,185.42,180.34,176.53,176.95,188.28,182.88,180.34,171.45,179.71,178.87,178.44,185.34,185.42,182.88,181.36,177.8,172.72,177.8,178.65,182.03,180.98,188.6,182.2,177.8,175.68,180.34,180.98,179.07,180.34,185.42,172.97,172.72,180.76,172.72,180.34,185.42,175.26,174.62,179.49,179.07,180.34,177.8,175.01,178.44,177.8,176.15,190.5,176.53,180.02,177.61,175.51,167.64,177.8,190.5,184.78,175.26,178.39,172.17,173.31,180.34,176.32,172.72,177.38,171.45,175.9,176.53,175.9,171.45,173.35,177.29,174.5,182.88,175.51,167,172.72,175.26,182.88,183.01,179.66,183.83,174.84,176.95,175.26,180.34,179.71,179.71,173.99,167.39,175.51,175.26,182.88,175.9,172.3,179.07,181.19,180.34,177.63,177.8,177.8,176.53,166.58,179.07,171.45,176.53,180.34,182.88,173.71,169.55,167.64,177.42,182.88,170.94,173.99,176.48,163.83,177.74,171.03,172.97,180.34,170.18,175.26,170.43,169.33,173.23,177.8,172.4,173.99,171.96,168.91,169.76,169.42,162.56,170.18,175.26,164.55,183.64,180.34,179.68,174.24,176.53,174.88,165.1,177.8,174.94,173.95,173.99,175.9,170.18,172.72,171.03,166.37,177.8,170.31,177.8,177.8,168.66,175.26,177.8,169.33,165.1,168.26,168.06,160.02,167.64,173.57,179.58,173.93,170.18,177.8,167.64,178.65,171.45,177.16,175.9,163.83,167.64,162.56,168.91]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Wzrost_ojca<\\/th>\\n      <th>Wzrost_matki<\\/th>\\n      <th>Średni_wzrost_synów<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Wzrost_ojca\",\"targets\":1},{\"name\":\"Wzrost_matki\",\"targets\":2},{\"name\":\"Średni_wzrost_synów\",\"targets\":3}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n### Opis danych\n\n| Nazwa zmiennej | Opis |\n|------------------------------------|------------------------------------|\n| Wzrost_ojca | Wzrost ojców w rodzinach Galtonów w centymetrach. |\n| Wzrost_matki | Wzrost matek w rodzinach Galtonów w centymetrach. |\n| Średni_wzrost_synów | Średni wzrost synów w kolejnych rodzinach Galtonów w centymetrach. |\n\n: Opis przerobionego zestawu danych \"GaltonFamilies\"\n\n### Funkcja\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Maslanka_Szymon_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n::: column-margin\nSchemat wzoru użytego w funkcji: $$\n\\scriptsize\nkategoria\\_wzrostu = \n\\begin{cases}\n\\text{Niski}, & \\text{gdy } \\text{round}(wzrost) < 170 \\\\\n\\text{Średni}, & \\text{gdy } \\text{round}(wzrost) = 170 \\\\\n\\text{Wysoki}, & \\text{gdy } \\text{round}(wzrost) > 170\n\\end{cases}\n$$ wzrost - Średni_wzrost_synów\n:::\n\n### Pętla łącząca 3 pliki `csv` w obiekt typu `tibble`\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata1 <- tibble(ID = 1:3, Name = c(\"A\", \"B\", \"C\"))\ndata2 <- tibble(ID = 4:6, Name = c(\"D\", \"E\", \"F\"))\ndata3 <- tibble(ID = 7:9, Name = c(\"G\", \"H\", \"I\"))\n\nwrite.csv(data1, \"file1.csv\", row.names = FALSE)\nwrite.csv(data2, \"file2.csv\", row.names = FALSE)\nwrite.csv(data3, \"file3.csv\", row.names = FALSE)\nfile_name <- vector(\"character\", 3)\nfor (i in 1:3) {\n  file_name[i] <- paste0(\"file\", i, \".csv\")\n}\n\ncombined <- file_name |> \n  map_dfr(read_csv)\n\ncombined\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 9 × 2\n     ID Name \n  <dbl> <chr>\n1     1 A    \n2     2 B    \n3     3 C    \n4     4 D    \n5     5 E    \n6     6 F    \n7     7 G    \n8     8 H    \n9     9 I    \n```\n\n\n:::\n:::\n\n\n\n### ggplot2\n\n------------------------------------------------------------------------\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Maslanka_Szymon_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nWidać że wraz ze wzrostem ojca wzrasta proporcjonalnie wzrost syna.\n\n------------------------------------------------------------------------\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Maslanka_Szymon_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\nMożna zauważyć, że wyniki tabeli zostały posortowane w kolejności malejącej, wraz ze zwiększeniem numeru pomiaru spada średni wzrost synów.\n\n### Regresja liniowa na przerobionym zestawie danych \"GaltonFamilies\"\n\n------------------------------------------------------------------------\n\n#### Szczegółowe informacje dotyczące modelu regresji wielorakiej\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Średni_wzrost_synów ~ Wzrost_ojca + Wzrost_matki, \n    data = b)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-12.9493  -2.7211   0.1447   3.0877  12.9324 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  55.15944   12.22268   4.513 1.17e-05 ***\nWzrost_ojca   0.41991    0.05230   8.029 1.35e-13 ***\nWzrost_matki  0.28920    0.05627   5.139 7.28e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.486 on 176 degrees of freedom\nMultiple R-squared:  0.3653,\tAdjusted R-squared:  0.3581 \nF-statistic: 50.64 on 2 and 176 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n- Residuals → różnica między wartością rzeczywistą (y) a wartością przewidywaną (ŷ) przez model. Jako że mediana wynosi ok. 0.14 cm — bardzo blisko zera, co jest dobrym znakiem regresji.\n\n- Współczynniki regresji (Coefficients) → Wzrost_ojca (0.42): Każdy dodatkowy centymetr wzrostu ojca zwiększa średni wzrost syna o około 0.42 cm, zakładając stały wzrost matki. Wzrost_matki (0.29): Każdy dodatkowy centymetr wzrostu matki zwiększa średni wzrost syna o około 0.29 cm, zakładając stały wzrost ojca. p-wartości wszystkich współczynników są bardzo małe (\\<\\< 0.001), co oznacza, że oba predyktory są istotne statystycznie.\n\n- Residual standard error: 4.486 → Średni błąd przewidywań wynosi około 4.5 cm wzrostu.\n\n- R^2^: 0.3653 → Model wyjaśnia około 36.5% zmienności średniego wzrostu synów na podstawie wzrostu ojca i matki.\n\n- Adjusted R^2^: 0.3581 → Skorygowana wersja R² (uwzględnia liczbę zmiennych) wynosi 35.8%.\n\n#### Tabele zawierające obserwacje wzbogacone o nowe kolumny oraz podsumowanie jakości modelu(parametry)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-8d1ef037b09834482db1\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-8d1ef037b09834482db1\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\"],[185.93,185.42,180.34,176.53,176.95,188.28,182.88,180.34,171.45,179.71,178.87,178.44,185.34,185.42,182.88,181.36,177.8,172.72,177.8,178.65,182.03,180.98,188.6,182.2,177.8,175.68,180.34,180.98,179.07,180.34,185.42,172.97,172.72,180.76,172.72,180.34,185.42,175.26,174.62,179.49,179.07,180.34,177.8,175.01,178.44,177.8,176.15,190.5,176.53,180.02,177.61,175.51,167.64,177.8,190.5,184.78,175.26,178.39,172.17,173.31,180.34,176.32,172.72,177.38,171.45,175.9,176.53,175.9,171.45,173.35,177.29,174.5,182.88,175.51,167,172.72,175.26,182.88,183.01,179.66,183.83,174.84,176.95,175.26,180.34,179.71,179.71,173.99,167.39,175.51,175.26,182.88,175.9,172.3,179.07,181.19,180.34,177.63,177.8,177.8,176.53,166.58,179.07,171.45,176.53,180.34,182.88,173.71,169.55,167.64,177.42,182.88,170.94,173.99,176.48,163.83,177.74,171.03,172.97,180.34,170.18,175.26,170.43,169.33,173.23,177.8,172.4,173.99,171.96,168.91,169.76,169.42,162.56,170.18,175.26,164.55,183.64,180.34,179.68,174.24,176.53,174.88,165.1,177.8,174.94,173.95,173.99,175.9,170.18,172.72,171.03,166.37,177.8,170.31,177.8,177.8,168.66,175.26,177.8,169.33,165.1,168.26,168.06,160.02,167.64,173.57,179.58,173.93,170.18,177.8,167.64,178.65,171.45,177.16,175.9,163.83,167.64,162.56,168.91],[199.39,191.77,190.5,190.5,190.5,187.96,187.96,185.42,185.42,185.42,185.42,185.42,184.66,182.88,182.88,182.88,182.88,182.88,182.88,184.15,182.88,182.88,180.34,180.34,180.34,180.34,180.34,180.34,182.12,180.34,181.61,181.61,180.34,182.12,180.34,181.61,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,177.8,177.8,177.8,177.8,177.8,179.07,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,177.8,179.07,177.8,177.8,177.8,179.07,179.07,177.8,177.8,177.8,179.07,178.56,179.07,177.8,177.8,177.8,177.8,175.26,175.26,175.26,175.26,175.26,175.26,176.53,175.26,176.53,175.26,175.26,176.53,175.77,175.26,175.26,175.26,175.26,175.26,176.53,175.26,176.53,175.26,175.26,176.53,175.26,175.26,175.26,175.26,174.5,173.99,173.99,172.72,172.72,172.72,172.72,173.99,172.72,173.99,172.72,172.72,172.72,172.72,173.99,172.72,172.72,172.72,172.72,173.99,172.72,173.23,172.72,174.5,172.72,172.72,172.72,172.72,172.72,173.99,172.72,170.18,170.18,170.18,170.18,170.18,170.18,170.18,171.45,170.18,170.18,170.18,171.45,170.18,167.64,167.64,167.64,167.64,168.91,167.64,167.64,168.91,168.91,167.64,167.64,167.64,167.64,165.1,165.1,165.1,165.1,165.1,165.1,165.1,165.1,165.1,166.37,166.37,162.56,162.56,162.56,162.56,157.48,158.75],[170.18,168.91,162.56,162.56,148.59,172.72,157.48,170.18,170.18,168.91,165.1,163.83,175.26,172.72,170.18,165.1,160.02,160.02,160.02,157.48,157.48,157.48,175.26,170.18,167.64,167.64,167.64,167.64,166.37,166.37,166.37,165.1,165.1,163.83,162.56,163.83,163.83,161.29,160.02,160.02,157.48,157.48,158.75,157.48,147.32,175.26,175.26,172.72,170.18,168.91,165.1,165.1,165.1,165.1,165.1,165.1,165.1,164.34,162.56,162.56,163.07,162.56,162.56,162.56,161.8,160.02,160.02,161.29,160.02,160.02,157.48,159.26,157.48,154.94,152.4,148.59,147.32,173.99,167.64,167.64,169.42,167.64,168.91,168.91,168.91,167.64,167.64,165.1,163.83,162.56,160.02,160.02,160.02,161.29,161.29,157.48,157.48,157.48,158.75,157.48,154.94,154.94,152.4,152.4,153.67,179.07,170.18,168.91,165.1,166.37,166.37,165.1,165.1,162.56,165.1,162.56,162.56,162.56,160.02,161.29,160.02,160.02,160.02,160.02,161.29,160.02,161.29,158.75,157.48,158.75,154.94,152.91,152.4,152.4,149.86,149.86,168.15,168.91,167.64,165.1,166.37,166.37,165.1,165.1,162.56,161.29,160.02,157.48,154.94,170.18,170.18,167.64,167.64,165.1,166.37,160.02,160.02,158.75,156.21,152.4,152.4,149.86,170.18,167.64,167.64,165.1,166.37,165.1,162.56,160.02,160.02,160.02,152.4,162.56,162.56,160.02,152.4,167.64,160.02],[188.1027271758045,184.5356984610185,182.1659619469915,182.1659619469915,178.1257793930903,184.0376967344122,179.6302248574291,182.2365382910137,182.2365382910137,181.8692489679317,180.767380998686,180.400091675604,183.386561470783,181.9045371399428,181.1699584937789,179.7008012014512,178.2316439091235,178.2316439091235,178.2316439091235,178.030355161577,177.4970652629597,177.4970652629597,181.5725359888719,180.1033786965442,179.3688000503804,179.3688000503804,179.3688000503804,179.3688000503804,179.7489564119748,179.0015107272985,179.5348006259158,179.1675113028339,178.6342214042165,179.0143777658109,177.8996427580527,178.800221979752,178.2669320811346,177.5323534349707,177.1650641118888,177.1650641118888,176.430485465725,176.430485465725,176.7977747888069,176.430485465725,173.4921708810695,180.5059561916372,180.5059561916372,179.7713775454734,179.0367988993095,178.6695095762276,178.1009315055992,177.5676416069818,177.5676416069818,177.5676416069818,177.5676416069818,177.5676416069818,177.5676416069818,177.3478464215155,176.833062960818,176.833062960818,176.9805570984335,177.3663528594353,176.833062960818,176.833062960818,176.6132677753516,176.6317742132715,176.6317742132715,176.465773637736,176.0984843146541,176.0984843146541,175.8971955671076,176.1978232417462,175.8971955671076,174.6293270223264,173.8947483761626,172.7928804069168,172.4255910838348,179.0720870713206,177.235640455911,177.235640455911,177.7504239166085,177.235640455911,177.6029297789929,178.1362196776103,177.6029297789929,177.7689303545283,177.235640455911,176.5010618097471,176.6670623852825,175.9806389496422,175.0319045174194,175.0319045174194,175.0319045174194,175.3991938405013,175.3991938405013,174.8306157698729,174.2973258712555,174.8306157698729,174.6646151943375,174.2973258712555,174.0960371237091,173.5627472250917,172.8281685789278,172.8281685789278,173.1954579020098,180.2221102510899,177.4369292034575,177.0696398803755,175.4344820125124,175.8017713355943,175.8017713355943,175.4344820125124,175.9677719111298,174.6999033663486,175.9677719111298,174.6999033663486,174.6999033663486,174.6999033663486,173.9653247201847,174.865903941884,173.9653247201847,173.9653247201847,173.9653247201847,173.9653247201847,174.865903941884,173.9653247201847,174.5467698293256,173.5980353971028,173.9781917586971,173.5980353971028,172.496167427857,171.9090829193087,171.7615887816931,171.7615887816931,171.5603000341466,171.0270101355293,175.2499749990571,175.4697701845235,175.1024808614415,174.3679022152777,174.7351915383596,174.7351915383596,174.3679022152777,174.9011921138951,173.6333235691138,173.2660342460319,172.89874492295,172.6974561754035,171.4295876306223,174.7704797103707,174.7704797103707,174.0359010642068,174.0359010642068,173.8346123166604,173.6686117411249,171.8321651257153,172.3654550243326,171.9981657012507,170.7302971564695,169.6284291872237,169.6284291872237,168.8938505410599,173.703899913136,172.9693212669721,172.9693212669721,172.2347426208083,172.6020319438902,172.2347426208083,171.5001639746444,170.7655853284806,170.7655853284806,171.2988752270979,169.0951392886064,170.4335841774097,170.4335841774097,169.6990055312459,167.4952695927543,169.769581875268,168.0991358353938],[-2.172727175804539,0.8843015389814752,-1.825961946991498,-5.6359619469915,-1.175779393090323,4.242303265587765,3.249775142570911,-1.896538291013655,-10.78653829101367,-2.159248967931717,-1.897380998685946,-1.960091675604019,1.953438529217038,3.51546286005717,1.710041506221046,1.659198798548772,-0.4316439091235225,-5.511643909123535,-0.4316439091235225,0.6196448384229711,4.532934737040335,3.482934737040324,7.027464011128046,2.096621303455748,-1.568800050380361,-3.688800050380365,0.9711999496196313,1.611199949619618,-0.6789564119747808,1.338489272701537,5.885199374084152,-6.197511302833902,-5.914221404216534,1.745622234189085,-5.179642758052665,1.539778020248036,7.153067918865389,-2.272353434970739,-2.54506411188882,2.324935888111185,2.639514534275037,3.909514534275047,1.002225211193121,-1.420485465724965,4.947829118930457,-2.705956191637227,-4.355956191637233,10.7286224545266,-2.50679889930953,1.350490423772413,-0.4909315055991783,-2.057641606981832,-9.927641606981837,0.2323583930181883,12.93235839301818,7.212358393018178,-2.307641606981832,1.042153578484516,-4.663062960817996,-3.523062960817981,3.359442901566467,-1.046352859435331,-4.113062960817985,0.5469370391820121,-5.163267775351642,-0.7317742132714784,-0.1017742132714829,-0.5657736377360436,-4.648484314654127,-2.748484314654121,1.392804432892376,-1.697823241746192,6.98280443289238,0.8806729776735835,-6.894748376162568,-0.07288040691676656,2.83440891616516,3.8079129286794,5.774359544089037,2.424359544089043,6.079576083391544,-2.39564045591095,-0.6529297789928989,-2.876219677610266,2.737070221007116,1.941069645471686,2.474359544089054,-2.511061809747105,-9.277062385282562,-0.4706389496421934,0.228095482580585,7.84809548258059,0.8680954825805998,-3.0991938405013,3.670806159498682,6.359384230127091,6.042674128744466,2.799384230127089,3.13538480566254,3.502674128744474,2.433962876290934,-6.982747225091686,6.241831421072163,-1.378168578927841,3.334542097990237,0.1178897489101018,5.443070796542514,-3.359639880375539,-5.884482012512393,-8.161771335594352,1.618228664405649,7.445517987487591,-5.027771911129776,-0.7099033663485557,0.5122280888702164,-10.86990336634855,3.040096633651444,-3.669903366348564,-0.9953247201846978,5.474096058116032,-3.78532472018469,1.294675279815294,-3.53532472018469,-4.635324720184684,-1.635903941883981,3.834675279815315,-2.146769829325564,0.3919646028972466,-2.018191758697128,-4.688035397102766,-2.736167427856998,-2.489082919308714,-9.201588781693147,-1.581588781693142,3.699699965853341,-6.47701013552927,8.39002500094287,4.870229815476534,4.577519138558472,-0.1279022152776861,1.794808461640372,0.1448084616403662,-9.267902215277701,2.898807886104947,1.306676430886171,0.6839657539680957,1.091255077050022,3.202543824596518,-1.249587630622273,-2.050479710370695,-3.740479710370693,-7.665901064206821,3.764098935793186,-3.524612316660352,4.131388258875091,5.967834874284733,-3.70545502433265,3.261834298749278,7.069702843530507,-0.2984291872237179,-4.528429187223736,-0.6338505410598714,-5.643899913135982,-12.94932126697211,-5.32932126697213,1.335257379191717,6.977968056109802,1.69525737919173,-1.320163974644402,7.034414671519443,-3.125585328480582,7.351124772902068,2.354860711393599,6.726415822590269,5.466415822590278,-5.869005531245847,0.1447304072456745,-7.209581875267986,0.8108641646061869],[0.0863597329303788,0.04454087172591888,0.03612286065230146,0.03612286065230146,0.07357277276491805,0.03883673510948624,0.0327405016843612,0.02565314908684793,0.02565314908684793,0.0232633808745571,0.01914028847270476,0.01878132841709399,0.03863405908697433,0.0268290854693156,0.02031685968101995,0.01338483257446873,0.01457603809463766,0.01457603809463766,0.01457603809463766,0.02119067624305097,0.01821785308974221,0.01821785308974221,0.032209233821794,0.01673480759611465,0.01204380671829496,0.01204380671829496,0.01204380671829496,0.01204380671829496,0.01300650814177157,0.01045985933814017,0.01218879315013054,0.01116494362069674,0.009383613997155362,0.01150859279749291,0.008754229432695789,0.01064879613043296,0.008815070695340576,0.009201090209221019,0.01015565302491624,0.01015565302491624,0.01358788477381677,0.01358788477381677,0.0116179178797815,0.01358788477381677,0.04762489333621917,0.03080058555021941,0.03080058555021941,0.0218383851128357,0.01490699283213201,0.01220284975053514,0.008040843703844669,0.007136632740764664,0.007136632740764664,0.007136632740764664,0.007136632740764664,0.007136632740764664,0.007136632740764664,0.006672688587549437,0.006297664930101064,0.006297664930101064,0.006303175355364287,0.007306667516283081,0.006297664930101064,0.006297664930101064,0.006441364162349146,0.008603299485401518,0.008603299485401518,0.00663973408352428,0.007489505276117489,0.007489505276117489,0.01193073961120003,0.008873438378889428,0.01193073961120003,0.01596561043819048,0.02324987525424701,0.0379840377721069,0.04391082935640026,0.02630643173818868,0.009723248018844286,0.009723248018844286,0.01309147451724703,0.009723248018844286,0.01202448068437315,0.0118943855523388,0.01202448068437315,0.009645548698360948,0.009723248018844286,0.006643888805296632,0.005945250371447505,0.005595603369664411,0.006577594848241398,0.006577594848241398,0.006577594848241398,0.005832615278750203,0.005832615278750203,0.009932127276658586,0.009590660104733863,0.009932127276658586,0.007830276456902621,0.009590660104733863,0.01508079231293307,0.01463453351790633,0.02170921508775882,0.02170921508775882,0.01791802328324761,0.04925005672770295,0.01545446566288804,0.01259313514663815,0.007905382190751278,0.009296002401042135,0.009296002401042135,0.007905382190751278,0.007055355832908616,0.006647247887679624,0.007055355832908616,0.006647247887679624,0.006647247887679624,0.006647247887679624,0.007419921741287992,0.006086894871709168,0.007419921741287992,0.007419921741287992,0.007419921741287992,0.007419921741287992,0.006086894871709168,0.007419921741287992,0.006448811500430075,0.0085678117268472,0.009596066858406254,0.0085678117268472,0.01505769391854487,0.02038142324678762,0.02192279224219333,0.02192279224219333,0.03059742210329125,0.03081869872252183,0.01536691544035772,0.01693045451481719,0.0144196386030843,0.01092111289712859,0.01241652473052146,0.01241652473052146,0.01092111289712859,0.00919396787882462,0.00945339534785291,0.00948108963197008,0.01001648595525725,0.01119761457034372,0.01723509164010607,0.0251381069854282,0.0251381069854282,0.01939918987658837,0.01939918987658837,0.01308681724566327,0.01729128438092352,0.01436728749014923,0.0119726070575879,0.01296330960849409,0.01870531382572477,0.0276126585138304,0.0276126585138304,0.03608939850175083,0.03208147882605891,0.02613297847101505,0.02613297847101505,0.02221528627265128,0.02392028135224819,0.02221528627265128,0.02032840223096755,0.02047232634596383,0.02047232634596383,0.01720052725294116,0.03013152340731629,0.02839726165390885,0.02839726165390885,0.02833160252270111,0.0403194740691581,0.05685976817983124,0.04340971176453707],[4.495070561451161,4.497833703341053,4.496155982406903,4.477373509645489,4.497405665846359,4.486444993284119,4.491413287742335,4.496008254845984,4.421857803990659,4.495320707351004,4.496021760271405,4.495865942192983,4.495831768751478,4.490280398955714,4.49645731148522,4.496580960946113,4.498233478671882,4.478730550438192,4.498233478671882,4.498104410376587,4.485040896600192,4.490498804268932,4.465824829777383,4.495513135356153,4.496771039020592,4.489597004323937,4.49774713098712,4.496684324939903,4.49805690799217,4.497203484318394,4.476027831348712,4.473614405193063,4.475870547936586,4.496395174026503,4.48112977431772,4.496831209322326,4.465445695382354,4.495042224751264,4.494195328850981,4.494883798075173,4.493865239942489,4.488501182435375,4.497708041835416,4.497054129997006,4.481997084199392,4.493552494300626,4.485901724465904,4.422981681097141,4.494300017304841,4.497180699202495,4.498199246045859,4.495644257355591,4.434855997661169,4.498319031372396,4.390059747046572,4.464952619320625,4.494945644279696,4.497659053036974,4.484433639007428,4.490413097730375,4.491134061573709,4.497652997146057,4.487527378907378,4.498162362219285,4.481278629719033,4.498010485228102,4.498346934169577,4.498148894194721,4.484504039139976,4.493516712190216,4.497106383479613,4.496505904451441,4.466899869486234,4.497852934722684,4.467334290855308,4.498350063319696,4.493013304731306,4.488884934611262,4.476916497201267,4.494582210682273,4.474502881343688,4.494671069276007,4.498079489529737,4.493032781243378,4.493534794153278,4.495936514582715,4.494424976784545,4.494320061852463,4.443022606509373,4.498212089248839,4.498320305798135,4.458799922516467,4.497871730374997,4.49221294113325,4.48973653380347,4.472333923991882,4.474875802376229,4.493323415846721,4.49205592472911,4.49047869974765,4.494531574446087,4.466813776007904,4.472987060618375,4.497120253416377,4.491156585259851,4.498344285545092,4.479199718535047,4.491087182067577,4.476129895277179,4.455441473626667,4.496674397735839,4.462721704161135,4.48215461007869,4.49803132316556,4.498185732980121,4.422159710405015,4.492440198277701,4.489733705877597,4.497719593909761,4.479163253796285,4.489175267362116,4.497280850339946,4.490348631216305,4.484583429729051,4.49664305028866,4.488934133302886,4.495406426039606,4.49825514327599,4.495740704905247,4.484251645585394,4.493523136168267,4.494334791167714,4.443030060248062,4.496728879020682,4.489376372721583,4.470776013904673,4.452714247627939,4.483002639942001,4.484829731354944,4.498343064980928,4.496281326541454,4.498340083866601,4.442852957264104,4.492963568981047,4.49725862486335,4.498053585691078,4.497589488391789,4.491760656352878,4.497344291992131,4.495613393775398,4.489228618171696,4.460127315210149,4.489167032414253,4.490351385223936,4.487308229978592,4.47534397326104,4.48951831320694,4.49150184811193,4.465885881356857,4.498295396771667,4.484938829528621,4.4980888249585,4.477402282151392,4.387627233292564,4.479791796961942,4.497195270283764,4.466556384374352,4.49648634559222,4.497223492851764,4.466152164988578,4.492014428010939,4.46329317520701,4.494720520098356,4.46867848856806,4.478776801079342,4.475781035355528,4.498339706705676,4.463211936032776,4.497916984289438],[0.008091283307391636,0.0006320936607186256,0.002147674246440871,0.02046072736427246,0.001963325831084544,0.01253423971043132,0.006122829092012578,0.001610211533137042,0.05208634472794973,0.001883516896308533,0.001186560723800955,0.001241634171370315,0.002642643399797801,0.005800144917131843,0.001025521582586794,0.0006271340849150947,4.633302763782645e-05,0.007554430825609117,4.633302763782645e-05,0.0001406955891483353,0.006433866657192502,0.003798427107831327,0.0281359053787264,0.001260565943859893,0.000503117911392151,0.002781664960380425,0.0001928199171932648,0.0005306809145033039,0.0001019675808393796,0.0003170552803606187,0.00716772538024496,0.007265904216646185,0.005541157127599482,0.0005945975911993176,0.003960053316162024,0.0004273285998863994,0.007605842105759738,0.0008018002721655344,0.001112289103360969,0.0009282013408438164,0.001611867593950832,0.003536119332355305,0.0001979043818491332,0.0004668257862843678,0.02129577837363119,0.003977593505217615,0.01030732291200951,0.04352446099513921,0.001599266166174699,0.0003778808926989783,3.262887015892471e-05,0.0005078085726795731,0.01182095987354453,6.475559386419622e-06,0.02005931163138477,0.006239002515821671,0.0006387005402795471,0.0001216818322741058,0.002297500828131992,0.001311456611844878,0.001193527148116491,0.0001344905145695553,0.001787490873044793,3.160732837561726e-05,0.002881949283490439,7.765519136507811e-05,1.502075626713886e-06,3.568360485499341e-05,0.002721772639185179,0.0009515149800291104,0.0003927525921047233,0.0004313848062159904,0.009871849759933583,0.0002118558720343707,0.01919272794600253,3.611639040980295e-06,0.006393608522713035,0.006665573903725478,0.00547711713828477,0.0009654692399938916,0.008230525173476666,0.000942730726458413,8.700678144315742e-05,0.001669650503622805,0.001528945587121401,0.0006138666601532021,0.001005703584067151,0.0007033531129966354,0.008578605211092856,2.076551814555533e-05,5.744851075533695e-06,0.006801018604695242,8.321093442818457e-05,0.0009390484010899984,0.0013173870822383,0.006788731929601864,0.005914575527936102,0.001315477887174389,0.001295486949710271,0.001987305813666835,0.001525797971940669,0.012175394405163,0.01464126006562315,0.0007137712860743458,0.003422261666486996,1.254504988631753e-05,0.00782557999651852,0.002415311915274668,0.004607648613680794,0.01045257834195674,0.0004108983188590085,0.007376540084866687,0.002996858032701259,5.624443205375358e-05,3.110583152138824e-05,0.01318658780537199,0.001031468195681633,0.001503108470402411,0.000123607261689418,0.003058933133290033,0.001787807218251473,0.000209139524408576,0.00155945563675784,0.002680863681445581,0.0002731874556536219,0.001834727591447908,0.0004987883978383893,2.218624331111436e-05,0.0006601453944093701,0.003173743597787822,0.0019251669906952,0.002179944320501641,0.03214559146477311,0.0009496923313150746,0.007383388093412477,0.02280339898109257,0.01848462103188265,0.00688406926595612,0.005153197880903272,3.025571045010546e-06,0.0006794145356665647,4.422689977151846e-06,0.0158859835334217,0.001303799334394615,0.0002725337532217238,7.489410113312708e-05,0.0002016314180833922,0.001946000086571816,0.0004616299091815201,0.00184248314083169,0.006131223910928873,0.01964136683657351,0.004735516420067027,0.002765317709474408,0.005063092342089148,0.008726183645496438,0.00278984476932913,0.002345412735087373,0.0160847610196002,4.308820572361247e-05,0.009921354762477326,0.0002585389908784906,0.01807097455913547,0.07654728501835464,0.01296521083690578,0.0006863436014321738,0.02025348898854585,0.001106325449107843,0.0006115671561001201,0.01749185610248626,0.003453366592128316,0.01594284071209114,0.002942876509615999,0.02254823822357244,0.0148919140463756,0.01712419680462792,1.519243024942623e-05,0.05504512820181212,0.0005167462945611901],[-0.5067588034117844,0.2016870647286465,-0.4146337067192759,-1.279796546067254,-0.2723352829467886,0.9646879437420502,0.7366573603968216,-0.4283399130667844,-2.43617800692819,-0.487077094981983,-0.4271051620899075,-0.4411407771831714,0.4441596528876896,0.7944593404980705,0.3851656566551332,0.3723987824090846,-0.09693883126177973,-1.237808081125526,-0.09693883126177973,0.1396296049311316,1.019895375871488,0.7836488365347551,1.592544640076022,0.4713769947004213,-0.3518701873069338,-0.8273704251542653,0.2178329278497717,0.361380169464057,-0.1523591254845213,0.2999728218171298,1.320103331996412,-1.389437838281673,-1.324733584332681,0.3914240780724916,-1.159826040393373,0.3451171920676749,1.60176472553934,-0.5089403014823389,-0.5702942528799564,0.5209682416685005,0.5924866654541127,0.8775610817362565,0.2247432273351008,-0.3188535944714741,1.130301740049136,-0.6127705875024383,-0.9864172387319762,2.418367935679081,-0.5630728650928004,0.3029293452331617,-0.1098898878734147,-0.460371797816549,-2.221186721330337,0.05198730953371883,2.893454848113779,1.613675767745436,-0.5163061981822983,0.2331144836215671,-1.042862007076351,-0.7879088361548616,0.7513184167464591,-0.2341285279839651,-0.9198582842633507,0.1223187126613187,-1.154812880361794,-0.1638464697583625,-0.0227875555800132,-0.1265531725852269,-1.040225600175161,-0.6150485948226259,0.3123778042276203,-0.3801995849751753,1.566101503258335,0.1979216278664818,-1.555286510215031,-0.01656545508717258,0.6462447493816914,0.8603191306339302,1.293627537513433,0.5431283319165012,1.364327299171126,-0.5366944056886369,-0.1464458625568288,-0.6450659101469455,0.6138984961175596,0.434840023743175,0.5543298125970549,-0.5616795869404982,-2.074383485813402,-0.1052180066482926,0.05101917486660853,1.755419928818194,0.1941709442273748,-0.6929512877910703,0.8207585541163707,1.424840670757105,1.353647333516487,0.6272111197913183,0.7017486500933718,0.7846502051133075,0.5467607971457826,-1.568235835562969,1.406895288912626,-0.3106362139924156,0.7501464456814078,0.02695421016206657,1.222953097570117,-0.7537518279207578,-1.317089885065309,-1.828084166335837,0.3624529623869549,1.666487621092296,-1.124855588071889,-0.1587929465569625,0.114599993459882,-2.431406957837738,0.6800163587878121,-0.8208930915757733,-0.2227233421357342,1.224114175432612,-0.8470403232747942,0.2897088753583325,-0.7910979414522976,-1.037244421471281,-0.3658198876391722,0.8580834746749021,-0.480146846775116,0.08776049481449581,-0.4521056888780146,-1.049646583177054,-0.6146402463122141,-0.5606535547969921,-2.074244623616257,-0.3565256071565999,0.8377185687060225,-1.46674894663052,1.884993098168414,1.095067917662197,1.02794024566047,-0.02867122985367245,0.4026381507221133,0.03248558966039251,-2.077541456955977,0.6492453304881383,0.2926943387055048,0.1532098520620501,0.2445096576953499,0.7179993488204066,-0.2810124871959311,-0.4629857781813755,-0.8445774423998575,-1.725841101836512,0.8474198401937629,-0.790961966819095,0.9291104155592843,1.340117767338882,-0.8310760656810141,0.7319458763163545,1.591054872167371,-0.06746917029661259,-1.023791817588107,-0.1439302926956536,-1.278920724580248,-2.925370634807128,-1.203942632701285,0.3010419972681708,1.574599300389978,0.3822062137746067,-0.2973523261332438,1.584540457898167,-0.70405522546772,1.653122581827725,0.533080165264468,1.521328734343782,1.236351674371457,-1.327361453015252,0.03293670611358512,-1.655029214456931,0.1848284602359498]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Średni_wzrost_synów<\\/th>\\n      <th>Wzrost_ojca<\\/th>\\n      <th>Wzrost_matki<\\/th>\\n      <th>.fitted<\\/th>\\n      <th>.resid<\\/th>\\n      <th>.hat<\\/th>\\n      <th>.sigma<\\/th>\\n      <th>.cooksd<\\/th>\\n      <th>.std.resid<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7,8,9]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Średni_wzrost_synów\",\"targets\":1},{\"name\":\"Wzrost_ojca\",\"targets\":2},{\"name\":\"Wzrost_matki\",\"targets\":3},{\"name\":\".fitted\",\"targets\":4},{\"name\":\".resid\",\"targets\":5},{\"name\":\".hat\",\"targets\":6},{\"name\":\".sigma\",\"targets\":7},{\"name\":\".cooksd\",\"targets\":8},{\"name\":\".std.resid\",\"targets\":9}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-1d3cf71f460201086893\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-1d3cf71f460201086893\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\"],[0.3652747160629877],[0.3580619287455216],[4.485555952293534],[50.64265726766413],[4.241800820928072e-18],[2],[-521.1316632066021],[1050.263326413204],[1063.012869636567],[3541.157347403448],[176],[179]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>r.squared<\\/th>\\n      <th>adj.r.squared<\\/th>\\n      <th>sigma<\\/th>\\n      <th>statistic<\\/th>\\n      <th>p.value<\\/th>\\n      <th>df<\\/th>\\n      <th>logLik<\\/th>\\n      <th>AIC<\\/th>\\n      <th>BIC<\\/th>\\n      <th>deviance<\\/th>\\n      <th>df.residual<\\/th>\\n      <th>nobs<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"scrollX\":true,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4,5,6,7,8,9,10,11,12]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"r.squared\",\"targets\":1},{\"name\":\"adj.r.squared\",\"targets\":2},{\"name\":\"sigma\",\"targets\":3},{\"name\":\"statistic\",\"targets\":4},{\"name\":\"p.value\",\"targets\":5},{\"name\":\"df\",\"targets\":6},{\"name\":\"logLik\",\"targets\":7},{\"name\":\"AIC\",\"targets\":8},{\"name\":\"BIC\",\"targets\":9},{\"name\":\"deviance\",\"targets\":10},{\"name\":\"df.residual\",\"targets\":11},{\"name\":\"nobs\",\"targets\":12}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### Automatyczne wykresy diagnostyczne\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Maslanka_Szymon_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n\n- Residuals vs Fitted nie ma wyraźnego wzoru\n\n- QQ-plot wygląda dobrze (reszty są prawie na linii)\n\n- Scale-Location jest równomierny\n\n- Residuals vs Leverage nie ma dramatycznych outlierów\n\n#### Dodatkowy interaktywny wykres zależności średniego wzrostu syna od wzrostów matki i ojca przy wykorzystaniu plot_ly\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-ae30ad82e253063b84b4\" style=\"width:100%;height:464px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-ae30ad82e253063b84b4\">{\"x\":{\"visdat\":{\"36207172213b\":[\"function () \",\"plotlyVisDat\"]},\"cur_data\":\"36207172213b\",\"attrs\":{\"36207172213b\":{\"x\":{},\"y\":{},\"z\":{},\"mode\":\"markers\",\"alpha_stroke\":1,\"sizes\":[10,100],\"spans\":[1,20],\"type\":\"scatter3d\"}},\"layout\":{\"margin\":{\"b\":40,\"l\":60,\"t\":25,\"r\":10},\"scene\":{\"xaxis\":{\"title\":\"Wzrost_ojca\"},\"yaxis\":{\"title\":\"Wzrost_matki\"},\"zaxis\":{\"title\":\"Średni_wzrost_synów\"}},\"hovermode\":\"closest\",\"showlegend\":false},\"source\":\"A\",\"config\":{\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"data\":[{\"x\":[199.38999999999999,191.77000000000001,190.5,190.5,190.5,187.96000000000001,187.96000000000001,185.41999999999999,185.41999999999999,185.41999999999999,185.41999999999999,185.41999999999999,184.66,182.88,182.88,182.88,182.88,182.88,182.88,184.15000000000001,182.88,182.88,180.34,180.34,180.34,180.34,180.34,180.34,182.12,180.34,181.61000000000001,181.61000000000001,180.34,182.12,180.34,181.61000000000001,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,180.34,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,179.06999999999999,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,179.06999999999999,177.80000000000001,177.80000000000001,177.80000000000001,179.06999999999999,179.06999999999999,177.80000000000001,177.80000000000001,177.80000000000001,179.06999999999999,178.56,179.06999999999999,177.80000000000001,177.80000000000001,177.80000000000001,177.80000000000001,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,176.53,175.25999999999999,176.53,175.25999999999999,175.25999999999999,176.53,175.77000000000001,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,176.53,175.25999999999999,176.53,175.25999999999999,175.25999999999999,176.53,175.25999999999999,175.25999999999999,175.25999999999999,175.25999999999999,174.5,173.99000000000001,173.99000000000001,172.72,172.72,172.72,172.72,173.99000000000001,172.72,173.99000000000001,172.72,172.72,172.72,172.72,173.99000000000001,172.72,172.72,172.72,172.72,173.99000000000001,172.72,173.22999999999999,172.72,174.5,172.72,172.72,172.72,172.72,172.72,173.99000000000001,172.72,170.18000000000001,170.18000000000001,170.18000000000001,170.18000000000001,170.18000000000001,170.18000000000001,170.18000000000001,171.44999999999999,170.18000000000001,170.18000000000001,170.18000000000001,171.44999999999999,170.18000000000001,167.63999999999999,167.63999999999999,167.63999999999999,167.63999999999999,168.91,167.63999999999999,167.63999999999999,168.91,168.91,167.63999999999999,167.63999999999999,167.63999999999999,167.63999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,166.37,166.37,162.56,162.56,162.56,162.56,157.47999999999999,158.75],\"y\":[170.18000000000001,168.91,162.56,162.56,148.59,172.72,157.47999999999999,170.18000000000001,170.18000000000001,168.91,165.09999999999999,163.83000000000001,175.25999999999999,172.72,170.18000000000001,165.09999999999999,160.02000000000001,160.02000000000001,160.02000000000001,157.47999999999999,157.47999999999999,157.47999999999999,175.25999999999999,170.18000000000001,167.63999999999999,167.63999999999999,167.63999999999999,167.63999999999999,166.37,166.37,166.37,165.09999999999999,165.09999999999999,163.83000000000001,162.56,163.83000000000001,163.83000000000001,161.28999999999999,160.02000000000001,160.02000000000001,157.47999999999999,157.47999999999999,158.75,157.47999999999999,147.31999999999999,175.25999999999999,175.25999999999999,172.72,170.18000000000001,168.91,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,165.09999999999999,164.34,162.56,162.56,163.06999999999999,162.56,162.56,162.56,161.80000000000001,160.02000000000001,160.02000000000001,161.28999999999999,160.02000000000001,160.02000000000001,157.47999999999999,159.25999999999999,157.47999999999999,154.94,152.40000000000001,148.59,147.31999999999999,173.99000000000001,167.63999999999999,167.63999999999999,169.41999999999999,167.63999999999999,168.91,168.91,168.91,167.63999999999999,167.63999999999999,165.09999999999999,163.83000000000001,162.56,160.02000000000001,160.02000000000001,160.02000000000001,161.28999999999999,161.28999999999999,157.47999999999999,157.47999999999999,157.47999999999999,158.75,157.47999999999999,154.94,154.94,152.40000000000001,152.40000000000001,153.66999999999999,179.06999999999999,170.18000000000001,168.91,165.09999999999999,166.37,166.37,165.09999999999999,165.09999999999999,162.56,165.09999999999999,162.56,162.56,162.56,160.02000000000001,161.28999999999999,160.02000000000001,160.02000000000001,160.02000000000001,160.02000000000001,161.28999999999999,160.02000000000001,161.28999999999999,158.75,157.47999999999999,158.75,154.94,152.91,152.40000000000001,152.40000000000001,149.86000000000001,149.86000000000001,168.15000000000001,168.91,167.63999999999999,165.09999999999999,166.37,166.37,165.09999999999999,165.09999999999999,162.56,161.28999999999999,160.02000000000001,157.47999999999999,154.94,170.18000000000001,170.18000000000001,167.63999999999999,167.63999999999999,165.09999999999999,166.37,160.02000000000001,160.02000000000001,158.75,156.21000000000001,152.40000000000001,152.40000000000001,149.86000000000001,170.18000000000001,167.63999999999999,167.63999999999999,165.09999999999999,166.37,165.09999999999999,162.56,160.02000000000001,160.02000000000001,160.02000000000001,152.40000000000001,162.56,162.56,160.02000000000001,152.40000000000001,167.63999999999999,160.02000000000001],\"z\":[185.93000000000001,185.41999999999999,180.34,176.53,176.94999999999999,188.28,182.88,180.34,171.44999999999999,179.71000000000001,178.87,178.44,185.34,185.41999999999999,182.88,181.36000000000001,177.80000000000001,172.72,177.80000000000001,178.65000000000001,182.03,180.97999999999999,188.59999999999999,182.19999999999999,177.80000000000001,175.68000000000001,180.34,180.97999999999999,179.06999999999999,180.34,185.41999999999999,172.97,172.72,180.75999999999999,172.72,180.34,185.41999999999999,175.25999999999999,174.62,179.49000000000001,179.06999999999999,180.34,177.80000000000001,175.00999999999999,178.44,177.80000000000001,176.15000000000001,190.5,176.53,180.02000000000001,177.61000000000001,175.50999999999999,167.63999999999999,177.80000000000001,190.5,184.78,175.25999999999999,178.38999999999999,172.16999999999999,173.31,180.34,176.31999999999999,172.72,177.38,171.44999999999999,175.90000000000001,176.53,175.90000000000001,171.44999999999999,173.34999999999999,177.28999999999999,174.5,182.88,175.50999999999999,167,172.72,175.25999999999999,182.88,183.00999999999999,179.66,183.83000000000001,174.84,176.94999999999999,175.25999999999999,180.34,179.71000000000001,179.71000000000001,173.99000000000001,167.38999999999999,175.50999999999999,175.25999999999999,182.88,175.90000000000001,172.30000000000001,179.06999999999999,181.19,180.34,177.63,177.80000000000001,177.80000000000001,176.53,166.58000000000001,179.06999999999999,171.44999999999999,176.53,180.34,182.88,173.71000000000001,169.55000000000001,167.63999999999999,177.41999999999999,182.88,170.94,173.99000000000001,176.47999999999999,163.83000000000001,177.74000000000001,171.03,172.97,180.34,170.18000000000001,175.25999999999999,170.43000000000001,169.33000000000001,173.22999999999999,177.80000000000001,172.40000000000001,173.99000000000001,171.96000000000001,168.91,169.75999999999999,169.41999999999999,162.56,170.18000000000001,175.25999999999999,164.55000000000001,183.63999999999999,180.34,179.68000000000001,174.24000000000001,176.53,174.88,165.09999999999999,177.80000000000001,174.94,173.94999999999999,173.99000000000001,175.90000000000001,170.18000000000001,172.72,171.03,166.37,177.80000000000001,170.31,177.80000000000001,177.80000000000001,168.66,175.25999999999999,177.80000000000001,169.33000000000001,165.09999999999999,168.25999999999999,168.06,160.02000000000001,167.63999999999999,173.56999999999999,179.58000000000001,173.93000000000001,170.18000000000001,177.80000000000001,167.63999999999999,178.65000000000001,171.44999999999999,177.16,175.90000000000001,163.83000000000001,167.63999999999999,162.56,168.91],\"mode\":\"markers\",\"type\":\"scatter3d\",\"marker\":{\"color\":\"rgba(31,119,180,1)\",\"line\":{\"color\":\"rgba(31,119,180,1)\"}},\"error_y\":{\"color\":\"rgba(31,119,180,1)\"},\"error_x\":{\"color\":\"rgba(31,119,180,1)\"},\"line\":{\"color\":\"rgba(31,119,180,1)\"},\"frame\":null}],\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n#### Testy modelu regresji\n\n##### Test Shapiro-Wilka\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  model$residuals\nW = 0.99549, p-value = 0.87\n```\n\n\n:::\n:::\n\n\n\nWartość statystyki testu (W) wynosi 0.99549, co sugeruje, że reszty są bardzo bliskie rozkładowi normalnemu.\n\np-wartość = 0.87 jest bardzo duża (znacznie większa niż 0.05), co oznacza, że nie możemy odrzucić hipotezy zerowej mówiącej, że rozkład zmiennej jest normalny.\n\n##### Test Durbin-Watson\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tDurbin-Watson test\n\ndata:  model\nDW = 1.8083, p-value = 0.07995\nalternative hypothesis: true autocorrelation is greater than 0\n```\n\n\n:::\n:::\n\n\n\np-wartość = 0.07995 jest \\> 0.05, więc nie możemy odrzucić hipotezy zerowej, która mówi, że autokorelacja jest zerowa. DW mieści się w przedziale od 1,5 do 2,5, oznacza to, że nie ma autokorelacji.\n\n##### Test Breusch-Pagan\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tstudentized Breusch-Pagan test\n\ndata:  model\nBP = 6.6963, df = 2, p-value = 0.03515\n```\n\n\n:::\n:::\n\n\n\np-wartość = 0.03515 jest \\< 0.05, co sugeruje, że istnieje dowód na heteroskedastyczność. Oznacza to, że wariancja reszt nie jest stała i może zmieniać się w zależności od wartości predyktorów.\n\n#### Podsumowanie regresji\n\nModel jest statystycznie istotny, ale jego dopasowanie (R^2^ = 36.5%) nie jest idealne jednak tak, małe R^2^ w przypadku tego modelu regresji może być w dużej mierze spowodowane innymi biologicznymi czynnikami, które należałoby dodać. Mimo że spełnia główne założenia regresji, heteroskedastyczność sugeruje, że model może wymagać dalszej poprawy, np. przez transformację zmiennych lub użycie bardziej zaawansowanego podejścia.\n\nOgólnie rzecz biorąc, model jest dobry, ale może być ulepszony, aby lepiej odwzorować zależności w danych.\n",
    "supporting": [
      "Maslanka_Szymon_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"Maslanka_Szymon_files/libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"Maslanka_Szymon_files/libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/leaflet-1.3.1/leaflet.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/proj4-2.6.2/proj4.min.js\"></script>\n<script src=\"Maslanka_Szymon_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/leaflet-binding-2.2.2/leaflet.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/datatables-binding-0.33/datatables.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"Maslanka_Szymon_files/libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n<script src=\"Maslanka_Szymon_files/libs/plotly-binding-4.10.4/plotly.js\"></script>\n<script src=\"Maslanka_Szymon_files/libs/typedarray-0.1/typedarray.min.js\"></script>\n<link href=\"Maslanka_Szymon_files/libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"Maslanka_Szymon_files/libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}